"""Render Agent - Format report with citations."""
from __future__ import annotations

from ..types import Source, SourceKind


def render_report(
    question: str,
    tldr: str,
    body: str,
    corpus_sources: list[Source],
    web_sources: list[Source],
) -> str:
    parts = []

    parts.append(f"# {question}\n")

    if tldr:
        parts.append(f"## TL;DR\n\n{tldr}\n")

    if body:
        parts.append(body)

    all_sources = corpus_sources + web_sources
    if all_sources:
        parts.append("\n## Sources\n")
        for src in all_sources:
            kind = "corpus" if src.kind == SourceKind.CORPUS else "web"
            parts.append(f"[{src.id}] **{src.title}** — {src.url} ({kind})")

    parts.append(f"\n---\n*Generated by Relay — research that ships like software.*")

    return "\n".join(parts)
