"""File writer that renders Jinja2 templates and writes generated files."""

import json
from datetime import datetime
from pathlib import Path
from typing import Any

from jinja2 import Environment, PackageLoader, select_autoescape


def write_generated_files(agent_spec: dict[str, Any], output_dir: str) -> list[str]:
    """
    Render Jinja2 templates and write files to output directory.
    
    Args:
        agent_spec: Parsed agent specification from OpenAI
        output_dir: Path to output directory
        
    Returns:
        List of created file paths
    """
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    
    # Set up Jinja2 environment
    env = Environment(
        loader=PackageLoader("scaff", "templates"),
        autoescape=select_autoescape(),
    )
    
    created_files = []
    timestamp = datetime.now().isoformat()
    
    # Add metadata to spec
    spec_with_meta = {
        **agent_spec,
        "generated_at": timestamp,
        "tool_count": len(agent_spec.get("tools", [])),
        "dependency_count": len(agent_spec.get("dependencies", [])),
    }
    
    # Render and write agent.py
    agent_template = env.get_template("agent.py.j2")
    agent_content = agent_template.render(spec_with_meta)
    agent_file = output_path / "agent.py"
    agent_file.write_text(agent_content, encoding="utf-8")
    created_files.append(str(agent_file))
    
    # Render and write tools.py
    tools_template = env.get_template("tools.py.j2")
    tools_content = tools_template.render(spec_with_meta)
    tools_file = output_path / "tools.py"
    tools_file.write_text(tools_content, encoding="utf-8")
    created_files.append(str(tools_file))
    
    # Render and write mcp.json
    mcp_template = env.get_template("mcp.json.j2")
    mcp_content = mcp_template.render(spec_with_meta)
    mcp_file = output_path / "mcp.json"
    mcp_file.write_text(mcp_content, encoding="utf-8")
    created_files.append(str(mcp_file))
    
    # Write requirements.txt
    deps = agent_spec.get("dependencies", [])
    deps_content = "\n".join(deps) + "\n" if deps else ""
    reqs_file = output_path / "requirements.txt"
    reqs_file.write_text(deps_content, encoding="utf-8")
    created_files.append(str(reqs_file))
    
    # Write .gitignore
    gitignore_content = """# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg

# Virtual environments
venv/
ENV/
env/

# IDE
.vscode/
.idea/
*.swp
*.swo
*~

# OS
.DS_Store
Thumbs.db

# Environment
.env
.env.local

# Generated
*.log
"""
    gitignore_file = output_path / ".gitignore"
    gitignore_file.write_text(gitignore_content, encoding="utf-8")
    created_files.append(str(gitignore_file))
    
    # Write .env.example
    env_example = """# OpenAI Configuration
OPENAI_API_KEY=your-api-key-here
OPENAI_MODEL=gpt-4o

# Agent Configuration
# Add your custom configuration here
"""
    env_file = output_path / ".env.example"
    env_file.write_text(env_example, encoding="utf-8")
    created_files.append(str(env_file))
    
    # Write README.md
    agent_name = agent_spec.get("agent_name", "agent")
    agent_desc = agent_spec.get("description", "An AI agent")
    readme_content = f"""# {agent_name.replace('-', ' ').title()}

{agent_desc}

## Overview

This AI agent was automatically generated by **scaff** at {timestamp}.

- **Agent Name:** {agent_name}
- **Tools:** {len(agent_spec.get('tools', []))}
- **Dependencies:** {len(agent_spec.get('dependencies', []))}

## Setup

1. **Install dependencies:**
   ```bash
   pip install -r requirements.txt
   ```

2. **Configure environment:**
   ```bash
   cp .env.example .env
   # Edit .env and add your OpenAI API key
   ```

3. **Set your OpenAI API key:**
   ```bash
   export OPENAI_API_KEY='your-api-key'
   ```

## Usage

Run the agent:
```bash
python agent.py
```

## Project Structure

```
.
├── agent.py              # Main agent with OpenAI tool-calling loop
├── tools.py              # Tool implementations (marked with TODO comments)
├── mcp.json              # MCP server configuration
├── requirements.txt      # Python dependencies
├── .env.example          # Example environment configuration
├── .gitignore            # Git ignore rules
└── README.md             # This file
```

## Agent Details

### System Prompt

```
{agent_spec.get('system_prompt', 'N/A')}
```

### Tools

The agent has access to the following tools:

{_format_tools(agent_spec.get('tools', []))}

### Dependencies

```
{chr(10).join(deps)}
```

## Implementation

To complete the implementation:

1. Open `tools.py`
2. Find the TODO comments for each tool
3. Replace the TODO with actual implementation logic
4. Test with `python agent.py`

### Example Tool Implementation

```python
def fetch_data(query: str) -> str:
    \"\"\"Fetch data based on query.\"\"\"
    # TODO: implement this tool
    # Replace the above with actual logic
    result = your_api_client.search(query)
    return str(result)
```

## Customization

Edit the `SYSTEM_PROMPT` in `agent.py` to customize the agent's behavior.

## Troubleshooting

**"OPENAI_API_KEY not set"**
- Make sure you've set your API key: `export OPENAI_API_KEY='your-key'`
- Or add it to `.env` file

**"Tool not found"**
- Make sure all tools are implemented in `tools.py`
- Check the tool names match between `agent.py` and `tools.py`

**API Rate Limits**
- If you hit rate limits, the agent will automatically retry with exponential backoff

## Advanced Usage

### Custom Model

Edit `agent.py` and change the model:
```python
model="gpt-4-turbo"  # or another model
```

### Adding New Tools

1. Add the tool definition to `SYSTEM_PROMPT`
2. Implement the function in `tools.py`
3. Add it to the `tools_map` in `agent.py`

## Generated by scaff

This agent was generated by **scaff** - the AI agent scaffolding tool.

For more information: https://github.com/your-repo/scaff
"""
    readme_file = output_path / "README.md"
    readme_file.write_text(readme_content, encoding="utf-8")
    created_files.append(str(readme_file))
    
    # Write MANIFEST.json (metadata)
    manifest = {
        "generated_at": timestamp,
        "agent_name": agent_spec.get("agent_name"),
        "description": agent_spec.get("description"),
        "tools": [{"name": t.get("name"), "description": t.get("description")} for t in agent_spec.get("tools", [])],
        "dependencies": agent_spec.get("dependencies", []),
        "model": "gpt-4o",
    }
    manifest_file = output_path / "MANIFEST.json"
    manifest_file.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    created_files.append(str(manifest_file))
    
    return created_files


def _format_tools(tools: list[dict[str, Any]]) -> str:
    """Format tools for README."""
    if not tools:
        return "No tools configured."
    
    formatted = []
    for i, tool in enumerate(tools, 1):
        name = tool.get("name", "unknown")
        desc = tool.get("description", "No description")
        formatted.append(f"{i}. **{name}**\n   - {desc}")
    
    return "\n\n".join(formatted)
